version: '3.6'
services:
  cli:
    build: .
    environment:
      - POSTGRES=postgres://postgres:password@postgres:5432/homework
      - NUMBER_OF_WORKERS=10
  postgres:
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db/init_docker_db.sh:/docker-entrypoint-initdb.d/docker_postgres_init.sh

